/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CalculadoraJNI */

#ifndef _Included_CalculadoraJNI
#define _Included_CalculadoraJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CalculadoraJNI
 * Method:    sumar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_sumar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     CalculadoraJNI
 * Method:    restar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_restar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     CalculadoraJNI
 * Method:    multiplicar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_multiplicar
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     CalculadoraJNI
 * Method:    dividir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_dividir
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
