/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include "CalculadoraJNI.h"

/*
 * Class:     CalculadoraJNI
 * Method:    sumar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_sumar (JNIEnv *env, jobject thisobject, jlong x, jlong y){
	return x+y;
}

/*
 * Class:     CalculadoraJNI
 * Method:    restar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_restar (JNIEnv *env, jobject thisobject, jlong x, jlong y){
	return x-y;
}

/*
 * Class:     CalculadoraJNI
 * Method:    multiplicar
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_multiplicar (JNIEnv *env, jobject thisobject, jlong x, jlong y){
	return x*y;
}

/*
 * Class:     CalculadoraJNI
 * Method:    dividir
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_CalculadoraJNI_dividir (JNIEnv *env, jobject thisobject, jlong x, jlong y){
	return x/y;
}
